# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 02:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initiates', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='initiative',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='initiates.Initiative'),
            preserve_default=False,
        ),
    ]
