# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiates', '0004_comment_initiative'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='city',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='initiative',
            name='customer',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='initiative',
            name='term',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='name',
            field=models.CharField(default='', max_length=300),
        ),
    ]
