# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiates', '0005_auto_20161119_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='pic',
            field=models.ImageField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
