# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiates', '0006_initiative_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='term',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
